### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TheWalker0** [MrKaKisen/pterodactyl-installer#2]
![schermata da 2019-01-27 15-15-59](https://user-images.githubusercontent.com/28711906/51802126-f382c700-2246-11e9-8fef-9b8a34eed6a6.png)
can u help me?

**Comment by MrKaKisen** [comment]
It seems like the panel is unable to connect to the node. Please make sure that the port is not blocked by any firewalls.

**Comment by MrKaKisen** [comment]
Closing this issue.
