### ISSUE TITLE
Install-panel.sh

### ISSUE THREAD

**Issue by Damchip** [MrKaKisen/pterodactyl-installer#4]
**Describe the bug**
Hi, Sorry for my english, but I'm trying to install your script on my Debian 9 Server and I've this message.

`bash <(curl -s https://raw.githubusercontent.com/MrKaKisen/pterodactyl-installer/master/install-panel.sh)
* Retrieving release information..
/dev/fd/63: line 510: syntax error near unexpected token `else'
/dev/fd/63: line 510: `  else'
`
Can you help me?

The daemon starting install work apparently.

**Comment by MrKaKisen** [comment]
Hi. Are you logged in as root? Putting `sudo` in-front of the command returns the error you are experiencing, I believe.

Log in as root using `sudo su` and then perform the bash command without sudo. Let me know if it works.

**Comment by MrKaKisen** [comment]
Sorry, my bad. Fixed it.

**Comment by Damchip** [comment]
Thanks now it's working.
