### ISSUE TITLE
Bash Error (LN 510) - Syntax Error

### ISSUE THREAD

**Issue by SizableRapter** [MrKaKisen/pterodactyl-installer#5]
**Describe the bug**
Note: Ran with Sudo // Same result as root

* Retrieving release information..
/dev/fd/63: line 510: syntax error near unexpected token `else'

**To Reproduce**
Bash the provided source

**Expected behavior**
Installation

**Screenshots**
N/A

**OS (please complete the following information):**
 - OS: Ubuntu
 - Installation: Daemon

**Additional context**

**Comment by MrKaKisen** [comment]
Sorry, my bad. It's now fixed, please try again.
